const Games = [
	{
		id: 1,
		title: 'Gears 5',
		imgURL: '../Images/gears-5.jpeg',
		console: 'Xbox Series X',
		videoID: 'SEpWlFfpEkU&t=7s',
	},

	{
		id: 2,
		title: 'Halo',
		imgURL: '../Images/halo.jpeg',
		console: 'Xbox Series X',
		videoID: 'MesnGRa16oA',
	},

	{
		id: 3,
		title: 'Hellblade',
		imgURL: '../Images/hellblade.jpeg',
		console: 'Xbox Series X',
		videoID: 'LCC5sEtOnkU',
	},
	{
		id: 4,
		title: 'It takes two',
		imgURL: '../Images/it-takes-two.jpeg',
		console: 'Xbox Series X',
		videoID: 'ohClxMmNLQQ',
	},
	{
		id: 5,
		title: 'A Plague Tale',
		imgURL: '../Images/a-plague-tale.jpeg',
		console: 'Xbox Series X',
		videoID: 'CtP6mNeN6yE',
	},
	{
		id: 6,
		title: 'Psychonauts',
		imgURL: '../Images/psychonauts.png',
		console: 'Xbox Series X',
		videoID: 'MeQu0kkcHHA',
	},
	{
		id: 7,
		title: 'Twelve Minutes',
		imgURL: '../Images/twelve-minutes.jpeg',
		console: 'Xbox Series X',
		videoID: 'XuL8FPhKr2Y',
	},
	{
		id: 8,
		title: 'Ori',
		imgURL: '../Images/Ori.jpeg',
		console: 'Xbox Series X',
		videoID: '2reK8k8nwBc',
	},
	{
		id: 9,
		title: 'Streets of Rage',
		imgURL: '../Images/streets-of-rage.jpeg',
		console: 'Xbox Series X',
		videoID: 'j_JtczD-9Ko',
	},
	{
		id: 10,
		title: 'Last of Us',
		imgURL: '../Images/last-of-us.jpeg',
		console: 'PS4',
		videoID: 'W01L70IGBgE',
	},
	{
		id: 11,
		title: 'Bloodborne',
		imgURL: '../Images/Bloodborne.jpeg',
		console: 'PS4',
		videoID: 'G203e1HhixY',
	},
	{
		id: 12,
		title: 'Genshin Impact',
		imgURL: '../Images/genshin.jpeg',
		console: 'PS4',
		videoID: 'HLUY1nICQRY',
	},
	{
		id: 13,
		title: 'Dragon Ball Z:KAKAROT',
		imgURL: '../Images/dragonball-Z.jpeg',
		console: 'PS4',
		videoID: '1Y-A1kUCvzY',
	},
	{
		id: 14,
		title: 'Ghost of Tsushima',
		imgURL: '../Images/Ghost-of-tsushima.jpeg',
		console: 'PS4',
		videoID: 'iqysmS4lxwQ',
	},
	{
		id: 15,
		title: 'Tomb Raider',
		imgURL: '../Images/tomb-raider.jpeg',
		console: 'PS4',
		videoID: 'CoLBrnC2F9g',
	},
	{
		id: 16,
		title: 'Naruto',
		imgURL: '../Images/naruto.jpeg',
		console: 'PS4',
		videoID: 'QdiB4waBJN4',
	},
	{
		id: 17,
		title: 'Overcooked',
		imgURL: '../Images/overcooked.jpeg',
		console: 'PS4',
		videoID: '0ZK7veYPEJQ',
	},
	{
		id: 18,
		title: 'Horizon',
		imgURL: '../Images/horizon.jpeg',
		console: 'PS4',
		videoID: 'u4-FCsiF5x4',
	},
	{
		id: 19,
		title: 'Uncharted',
		imgURL: '../Images/uncharted.jpeg',
		console: 'PS4',
		videoID: '-mH2SVyBMAQ',
	},
	{
		id: 20,
		title: 'Persona 5 Royal',
		imgURL: '../Images/persona.jpeg',
		console: 'PS4',
		videoID: 'QnDzJ9KzuV4',
	},
	{
		id: 21,
		title: 'Ratchet',
		imgURL: '../Images/ratchet.jpeg',
		console: 'PS4',
		videoID: '55PRv_e00wc',
	},
	{
		id: 22,
		title: 'Spider-Man',
		imgURL: '../Images/spider-man.jpeg',
		console: 'PS4',
		videoID: 'q4GdJVvdxss',
	},
];
export default Games;
